FROM centos:8
LABEL APP="studentapp"
LABEL Author="Abhishek"
ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.100/bin/apache-tomcat-8.5.100.tar.gz ./
RUN yum install java -y
RUN tar -xvzf /apache-tomcat-8.5.100.tar.gz -C /opt
WORKDIR /opt/apache-tomcat-8.5.100
COPY student.war webapps/student.war
COPY context.xml conf/context.xml
ADD  https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar lib/mysql-connector.jar
EXPOSE 8080
CMD ["./bin/catalina.sh","run"] 
